### Devolución esperada: código 200, 10 productos ###

GET http://localhost:8080/api/products/

### Devolución esperada: código 200, 5 productos ###

GET http://localhost:8080/api/products/?limit=5

### Devolución esperada: código 200, 1 único producto con id = f0a8eed4-021a-44d5-84c8-7a6980efb21f ###

GET http://localhost:8080/api/products/f0a8eed4-021a-44d5-84c8-7a6980efb21f

### Devolución esperada: código 404 ###

GET http://localhost:8080/api/products/1

### Devolución esperada: código 200, array de productos con el nuevo producto incluido ###

POST http://localhost:8080/api/products/
content-type: application/json

{
    "code": "sampleProduct",
    "title": "Sample Product",
    "description": "This is a sample product",
    "price": "34",
    "stock": "10"
}

### Devolución esperada: código 400, error de validación ###

POST http://localhost:8080/api/products/
content-type: application/json

{
    "code": "sampleProduct",
    "title": "Sample Product",
    "description": "This is a sample product",
    "price": "a",
    "stock": "10"
}

### Devolución esperada: código 200, producto actualizado ###

PUT http://localhost:8080/api/products/f0a8eed4-021a-44d5-84c8-7a6980efb21f
content-type: application/json

{
    "code": "sampleProduct2",
    "title": "Sample Product",
    "description": "This is a sample product",
    "price": "a",
    "stock": "10"
}

### Devolución esperada: código 404, producto no encontrado ###

PUT http://localhost:8080/api/products/1
content-type: application/json

{
    "code": "sampleProduct2",
    "title": "Sample Product",
    "description": "This is a sample product",
    "price": "a",
    "stock": "10"
}

### Devolución esperada: código 404, producto no encontrado ###

DELETE http://localhost:8080/api/products/1

### Devolución esperada: código 204, lista de productos sin el eliminado ###

DELETE http://localhost:8080/api/products/f0a8eed4-021a-44d5-84c8-7a6980efb21f




