import GitHubStrategy from 'passport-github2'
import { UserManager } from '../dao/mongoose/user.manager.js'
import 'dotenv/config'
import { CartManager } from '../dao/mongoose/cartManager.js'

const CALLBACK_URL = 'http://localhost:8080/api/auth/github/callback'
const userManager = new UserManager()
const cartManager = new CartManager()

// Callback when github strategy is used to log in
const auth = async (accessToken, refreshToken, profile, done) => {
  // accessToken y refreshToken are generated by github. Related with JWT

  try {
    const { _json: { email } } = profile

    if (!email) {
      console.log('User email is not public')
      return done(null, false)
    }

    let user = await userManager.getByEmail(email)

    if (!user) {
      const cart = await cartManager.create()
      const _user = await userManager.create({
        firstname: '',
        lastname: '',
        email,
        password: '',
        role: 'user',
        age: '',
        cart
      })
      user = _user._doc
    }
    done(null, user)
  } catch (err) {
    console.error(err)
    done(err, false)
  }
}

const gitHubHandler = new GitHubStrategy(
  {
    clientID: process.env.GITHUB_CLIENT_ID,
    clientSecret: process.env.GITHUB_CLIENT_SECRET,
    callbackURL: CALLBACK_URL
  },
  auth
)

export default gitHubHandler
